name: Deploy to AWS S3
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Setup Node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install playwright && machine dependencies
      run: npx playwright install --with-deps


    - name: Install dependencies
      run: npm install

    - name: Run tests (CI optimized)
      run: npm run test:ci

    - name: Build application in a static setup
      run: npm run build:static

    - name: Upload production build
      uses: actions/upload-artifact@v4.6.2
      with:
        name: production-build
        path: build/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        
      - name: Download production build
        uses: actions/download-artifact@v4.1.7
        with:
          name: production-build
          path: build/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.7

      - name: Terraform Init
        working-directory: ./infra/terraform
        run: terraform init

      - name: Apply Basic Infrastructure with Import Handling
        working-directory: ./infra/terraform
        run: |
          set +e  # Don't exit on error, we want to handle it
          echo "🎯 Applying basic infrastructure first..."
          
          # Try targeted apply first - this will fail if bucket exists but isn't imported
          terraform apply -target=aws_s3_bucket.website -target=aws_s3_bucket_website_configuration.website -target=aws_s3_bucket_public_access_block.website -target=aws_s3_bucket_policy.website -target=aws_acm_certificate.website -auto-approve
          APPLY_RESULT=$?
          
          if [ $APPLY_RESULT -ne 0 ]; then
            echo "⚠️  Apply failed - likely due to existing S3 bucket. Attempting import..."
            
            # Check if S3 bucket exists and import it
            if aws s3api head-bucket --bucket ${{ secrets.DOMAIN_NAME }} 2>/dev/null; then
              echo "✅ S3 bucket exists, importing..."
              terraform import aws_s3_bucket.website ${{ secrets.DOMAIN_NAME }}
              
              # Now retry the targeted apply
              echo "🔄 Retrying basic infrastructure apply..."
              set -e  # Re-enable exit on error for the retry
              terraform apply -target=aws_s3_bucket.website -target=aws_s3_bucket_website_configuration.website -target=aws_s3_bucket_public_access_block.website -target=aws_s3_bucket_policy.website -target=aws_acm_certificate.website -auto-approve
            else
              echo "❌ Apply failed and bucket doesn't exist - this is unexpected"
              set -e
              exit 1
            fi
          else
            echo "✅ Basic infrastructure applied successfully"
          fi
        env:
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}

      - name: Terraform Plan (Full)
        working-directory: ./infra/terraform
        run: terraform plan
        env:
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}

      - name: Terraform Apply (Full)
        working-directory: ./infra/terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}

      - name: Sync files to S3
        run: |
          aws s3 sync build/ s3://${{ secrets.DOMAIN_NAME }}/ --delete --exact-timestamps
          
      - name: Invalidate CloudFront
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[0]=='${{ secrets.DOMAIN_NAME }}'].Id" --output text)
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" 
